import type { AuditAction } from "@/types/firestore";

export const AUDIT_ACTION_LABELS: Record<AuditAction, string> = {
  RAFFLE_CREATED: "Raffle created",
  RAFFLE_UPDATED: "Raffle updated",
  RAFFLE_PUBLISHED: "Raffle published",
  RAFFLE_CANCELLED: "Raffle cancelled",
  TERMS_CREATED: "Terms drafted",
  TERMS_UPDATED: "Terms updated",
  TERMS_PUBLISHED: "Terms published",
  TERMS_ACCEPTED: "Terms accepted by participant",
  PRIZE_CREATED: "Prize created",
  PRIZE_UPDATED: "Prize updated",
  REGISTRATION_CREATED: "Registration created",
  PAYMENT_SUBMITTED: "Payment receipt submitted",
  PAYMENT_APPROVED: "Payment approved",
  PAYMENT_REJECTED: "Payment rejected",
  ENTRY_CREATED: "Entry created",
  ENTRY_APPROVED: "Entry approved",
  ENTRY_DISQUALIFIED: "Entry disqualified",
  DRAW_STARTED: "Draw started",
  DRAW_PRESENTATION_UPDATED: "Draw presentation updated",
  WINNER_SELECTED: "Winner selected",
  WINNER_VERIFIED: "Winner verified",
  WINNER_DISQUALIFIED: "Winner disqualified",
  REDRAW_STARTED: "Redraw started",
  PRIZE_ASSIGNED: "Prize assigned",
  PRIZE_CLAIMED: "Prize claimed",
  ADMIN_ROLE_CHANGED: "Admin role changed",
  USER_DEACTIVATED: "User deactivated",
  USER_REACTIVATED: "User reactivated",
};
